---
- name: login to aws
  command: bash -c "sudo $(aws ecr get-login --region eu-west-1 --no-include-email)"

- name: pull image
  command: bash -c "sudo docker pull 133506877714.dkr.ecr.eu-west-1.amazonaws.com/pronto-dashboard-nginx:proxy"

- name: run image
  command: bash -c "sudo docker run -d -p 80:80 133506877714.dkr.ecr.eu-west-1.amazonaws.com/pronto-dashboard-nginx:proxy"
