kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  # host path This is ideal for minikube but is not ideal for a production application.
  hostPath:
    path: /data/postgres-pv

