apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 133506877714.dkr.ecr.eu-west-1.amazonaws.com/pronto-dashboard-nginx:k8s
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-assets
              mountPath: /assets
            - name: static-media
              mountPath: /media

      volumes:
        - name: static-assets
          persistentVolumeClaim:
            claimName: static-assets-pvc
        - name: static-media
          persistentVolumeClaim:
            claimName: static-media-pvc
