apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: dev
  labels:
    app: db
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: dev
  labels:
    type: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: postgres-pv

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: db-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: db
          image: postgres:9.6.2-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres

            - name: POSTGRES_USER
              value: postgres

          volumeMounts:
            - name: postgres-data-dev
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-data-dev
          persistentVolumeClaim:
            claimName: postgres-pvc
